# list of all new entities and their details

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: service-chain-svc1
  description: Calls the first service in the chain (Spring Boot).
  tags:
    - springboot
    - backend
    - api
  links:
    - url: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/catalog-info.yaml
spec:
  type: openapi
  lifecycle: experimental
  owner: bhn
  definition: 
    $text: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/packages/app/src/openapi/svc1-openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: service-chain-svc2
  description: Calls the second service in the chain (Spring Boot).
  tags:
    - springboot
    - backend
    - api
  links:
    - url: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/catalog-info.yaml
spec:
  type: openapi
  lifecycle: experimental
  owner: bhn
  definition: 
    $text: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/packages/app/src/openapi/svc2-openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: service-chain-svc3
  description: Calls the third service in the chain (Spring Boot).
  tags:
    - springboot
    - backend
    - api
  links:
    - url: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/catalog-info.yaml
spec:
  type: openapi
  lifecycle: experimental
  owner: bhn
  definition: 
    $text: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/packages/app/src/openapi/svc3-openapi.yaml