# list of all entities and their details

# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: backstage-app
#   description: An example of a Backstage application.
#   # Example for optional annotations
#   # annotations:
#   #   github.com/project-slug: backstage/backstage
#   #   backstage.io/techdocs-ref: dir:.
# spec:
#   type: website
#   owner: john@example.com
#   lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: service-chain-svc1
  description: Calls the first service in the chain (Spring Boot).
  owner: kelley.le2@bhn.com
  tags:
    - springboot
    - backend
    - api
  links:
    - url: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/catalog-info.yaml
spec:
  type: openapi
  lifecycle: experimental
  owner: kelley.le2@bhn.com
  definition: 
    $text: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/packages/app/src/catalog/svc1-openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: service-chain-svc2
  description: Calls the second service in the chain (Spring Boot).
  owner: kelley.le2@bhn.com
  tags:
    - springboot
    - backend
    - api
  links:
    - url: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/catalog-info.yaml
spec:
  type: openapi
  lifecycle: experimental
  owner: kelley.le2@bhn.com
  definition: 
    $text: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/packages/app/src/catalog/svc2-openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: service-chain-svc3
  description: Calls the third service in the chain (Spring Boot).
  owner: kelley.le2@bhn.com
  tags:
    - springboot
    - backend
    - api
  links:
    - url: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/catalog-info.yaml
spec:
  type: openapi
  lifecycle: experimental
  owner: kelley.le2@bhn.com
  definition: 
    $text: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/packages/app/src/catalog/svc3-openapi.yaml