# List of all new entities and their details to be imported

# Services
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: svc1
  description: 1st service in chain
  annotations:
    backstage.io/techdocs-ref: dir:./docs/service-chain-docs
spec:
  type: service
  lifecycle: experimental
  owner: bhn
  providesApis: [svc1-api]
  consumesApis: [svc2-api]
  dependsOn:
    - component:svc2
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: svc2
  description: 2nd service in chain
  annotations:
    backstage.io/techdocs-ref: dir:./docs/service-chain-docs
spec:
  type: service
  lifecycle: experimental
  owner: bhn
  providesApis: [svc2-api]
  consumesApis: [svc3-api]
  dependsOn:
    - component:svc3
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: svc3
  description: 3rd service in chain
  annotations:
    backstage.io/techdocs-ref: dir:./docs/service-chain-docs
spec:
  type: service
  lifecycle: experimental
  owner: bhn
  providesApis: [svc3-api]
---

# Openapis
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: svc1-api
  description: Service 1 API
  annotations:
    backstage.io/techdocs-ref: dir:./docs/service-chain-docs
  tags:
    - springboot
    - backend
    - api
  links:
    - url: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/catalog-info.yaml
spec:
  type: openapi
  lifecycle: experimental
  owner: bhn
  definition: 
    $text: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/packages/app/src/openapi/svc1-openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: svc2-api
  description: Service 2 API
  annotations:
    backstage.io/techdocs-ref: dir:./docs/service-chain-docs
  tags:
    - springboot
    - backend
    - api
  links:
    - url: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/catalog-info.yaml
spec:
  type: openapi
  lifecycle: experimental
  owner: bhn
  definition: 
    $text: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/packages/app/src/openapi/svc2-openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: svc3-api
  description: Service 3 API
  annotations:
    backstage.io/techdocs-ref: dir:./docs/service-chain-docs
  tags:
    - springboot
    - backend
    - api
  links:
    - url: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/catalog-info.yaml
spec:
  type: openapi
  lifecycle: experimental
  owner: bhn
  definition: 
    $text: https://github.com/kelleyle-bhn/my-backstage-app/blob/main/packages/app/src/openapi/svc3-openapi.yaml
---

# Documentation
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: standalone-docs
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    backstage.io/techdocs-ref: dir:./docs/standalone-docs
spec:
  type: documentation
  lifecycle: experimental
  owner: bhn
