# makes documentation

site_name: 'Service Chain Documentation'
site_description: This is where the documentation for the service chain is.
plugins:
  - techdocs-core

nav:
  - Home: index.md
  - About: about.md